Fr] create an interface contact dto repository #18
JavaRush-GNEW/contact-manager pull request #38
Opened 2024-11-04 01:26 UTC by DenysBurduzhan

Check pls

2024-11-04 18:26 UTC, DenysBurduzhan commented
Да, добавил в comit ContactDtoRepository.  Класс JsonContactDtoRepository оставил как вспомогательный. Все работает. В случае чего, можно будет сократить, но уже потом. 
Створи окрему папку repository. - done

2024-11-04 19:26 UTC, dRaider-bitrek requested changes
Знову стопе.
Ти завантажуєш в коміті це https://github.com/JavaRush-GNEW/contact-manager/pull/38/files

В цій тасці треба зробити тільки інтерфейс. Для реалізації вже є окрема таска. Всі інші файли треба прибрати. gitignore так взагалі твої особисті файли.
.idea/.gitignore
.idea/encodings.xml
.idea/misc.xml
.idea/vcs.xml
demo.st

Через це інші не зможуть втягнути до себе цей коміт.
![image](https://github.com/user-attachments/assets/a1fd0cf9-6884-4284-8793-2011216ee133)


src/main/java/ua/com/javarush/gnew/m2/dto/ContactDto.java
src/main/java/ua/com/javarush/gnew/m2/Repository/JsonContactDtoRepository.java

2. По самому файлу ContactDtoRepository гадаю потрібно додати методи для зберігання та завантаження переліка контактів (saveAll, findAll).

2024-11-05 04:55 UTC, DenysBurduzhan commented
мои познавания гита продолжаются. Так, там теперь только интерфейс. Если что не ок, созвонимся сегодня и разберемся

2024-11-05 15:25 UTC, dRaider-bitrek requested changes
Дублікат

2024-11-05 15:26 UTC, closed without merging