Create a service class to access localized messages.
JavaRush-GNEW/contact-manager pull request #91
Opened 2024-11-17 17:07 UTC by DenysBurduzhan

2024-11-17 17:12 UTC, DenysBurduzhan commented
Если правильно понял, в тикете создаем пока просто класс. Заполняем файлы текстом потом?

2024-11-20 16:56 UTC, dRaider-bitrek approved these changes

2024-11-20 17:00 UTC, dRaider-bitrek commented
@oleksandr-jr Зроби будласка review.

2024-11-21 08:35 UTC, oleksandr-jr requested changes
In general, looks good, but there are a couple of things.
1. Fallback language (Highly suggested)
2. Accessibility of the `getMessage` method.
3. I'm not sure about multithreading here. Maybe you will need to deal with changes later.

Please think on how you will use this class, more specifically, how you get an object of this class all around the project. Currently, you have to create one every time or inject it.

Approaches to consider:
1. Global context class (Maybe already implemented)
2. Singleton
4. Static utility class
5. Implement some kind of Dependency Injection.
6. Service Locator Pattern

2024-11-21 08:35 UTC, oleksandr-jr commented on src/main/java/ua/com/javarush/gnew/m2/service/LocalizationService.java
> +    }
Maybe it's a good idea to add a `fallback` locale here in the case we can't find this message in the current locale.

Example:
We are looking for a Ukrainian word 'Котактʼ using key, but we can't find it. Then we simply show this word in English before throwing an exception. So in this way we reduce the amount of exceptions and have a “base language”.

2024-11-22 19:01 UTC, oleksandr-jr approved these changes

2024-11-23 14:06 UTC, merged